const data = {
	logo: "assets/logo/logo.webp",
	nav: [
		{
			id: "nav1",
			title: "Funds",
			navItems: ["ESG"],
		},
		{
			id: "nav2",
			title: "Insights",
			navItems: ["Intelligence", "VS Blog"],
		},
		{
			id: "nav3",
			title: "Podcasts",
			navItems: [],
		},
		{
			id: "nav4",
			title: "Media",
			navItems: [],
		},
		{
			id: "nav5",
			title: "Seed",
			navItems: [],
		},
		{
			id: "nav6",
			title: "Info",
			navItems: ["Team", "Timeline", "Careers", "Contract"],
		},
	],
	events: [
		{
			id: "event1",
			title: "Lendlt Fintech 2022",
			text: "We'll attend the biggest USA's leading event for innovation in financial services in New York.",
			date: "25-26 May 2022",
			link: "https://www.lendit.com/usa/2022/",
			background: "assets/hover/hover-1.gif",
		},
		{
			id: "event2",
			title: "Business Forum for Alt Funds",
			text: "We'll participate and speak about importance of ESG, the post-pandemic world, key legal developments, crypto and other topics.",
			date: "18May 2022",
			link: "https://www.wilsonwillis.com/business-forum-2022",
			background: "assets/hover/hover-2.gif",
		},
		{
			id: "event3",
			title: "AIM Summit",
			text: `We'll discussing "Hedge Funds - What investors currently are looking for from their hedge fund allocation". `,
			date: "16-17 May 2022",
			link: "https://www.aimsummit.com/",
			background: "assets/hover/hover-3.gif",
		},
		{
			id: "event4",
			title: "FTT Embedded Finance",
			text: "Our Head of Capital Markets, Patrizia Lando, spoke about Buy Now Later at the FTT Embedded Finance conference in London.",
			date: "26 April 2022",
			link: "https://www.fintechtalents.com/",
			background: "assets/hover/hover-4.gif",
		},
		{
			id: "event5",
			title: "FTT Lending 3.0 2022",
			text: `We participated and discussing "The rise of the specialist lender" at the Fintech Talents Lending 3.0 event in London.`,
			date: "30 March 2022",
			link: "https://www.fintechtalents.com/ftt-lending-2022/",
			background: "assets/hover/hover-5.gif",
		},
		{
			id: "event6",
			title: "HFM European Tech",
			text: "At the HFM Global European Technology Summit we took part for a Fireside chat on the application of Alternative Data Sets.",
			date: "1 Mar 2022",
			link: "https://www.hfmeutechnologysummit.com/page/1960379/apply-to-attend",
			background: "assets/hover/hover-6.gif",
		},
	],
	banner: [
		{
			id: "banner1",
			title: "Investing in a",
			title2: "Digital Future",
			subtitle: "Quant Fintech Investments",
			text: "",
			button: "Explore",
			background: "assets/banner/banner-video-1.mp4",
			type: "video",
		},
		{
			id: "banner2",
			title: "Scenarios",
			title2: "",
			subtitle: "The Market Economy In 2025: A Visualization Exercise ",
			text: "Emergence of New Capital Markets. To any market participant who has been more than 10 years in activity, financial markets are unrecognisable, lampooning the laws of physics...",
			button: "Read",
			background: "assets/banner/banner-video-2.mp4",
			type: "video",
		},
		{
			id: "banner3",
			title: "Digital Future",
			title2: "",
			subtitle: "",
			text: "Use Of Digital Technology To Build Resilient Portfolios. Going Beyond 60/40 Traditional Asset Allocation.",
			button: "More",
			background: "assets/banner/banner.webp",
			type: "image",
		},
		{
			id: "banner4",
			title: "Scenarios",
			title2: "",
			subtitle: "",
			text: "At a time in which bonds are no longer bonds but rather tax bills, and equities are as expensive as washing machines going on auction at 50 thousand dollars, what role is left to play for us rationale investors?",
			button: "Read",
			background: "assets/banner/banner-2.webp",
			type: "image",
		},
		{
			id: "banner5",
			title: "Podcast",
			title2: "",
			subtitle: "",
			text: "Fasanara discusses the unreliability of asset prices. Tech stocks, market intervention. Incidental triggers for a big market correction. Non-linearity, Risk-Parity and fake markets.",
			button: "Watch",
			background: "assets/banner/banner-1.webp",
			type: "image",
		},
	],
	fasanaraCards: [
		{
			id: "box1",
			title: "Fasanara Fintech",
			text: "Alternative Credit Digital Lending",
		},
		{
			id: "box2",
			title: "Fasanara Quant",
			text: "Quant Network. Liquid Assets Trading",
		},
		{
			id: "box3",
			title: "Fasanara Digital",
			text: "Digital Assets Arbitrage",
		},
		{
			id: "box4",
			title: "Fasanara Ventures",
			text: "New Technologies Co-Investments",
		},
	],
	insightsCards: [
		{
			id: "insights1",
			title: "Scenarios | Jan 2021",
			text: "Digital Future. Use Of Digital Technology To Build Resilient Portfolios.",
			image: "assets/card/card-1.gif",
		},
		{
			id: "insights2",
			title: "Scenarios | Oct 2020",
			text: "The Market Economy In 2025: A Visualization Exercise",
			image: "assets/card/image-2.webp",
		},
		{
			id: "insights3",
			title: "Scenarios | Oct 2019",
			text: "How To Navigate The Cliff Edge In Markets",
			image: "assets/card/image-3.webp",
		},
		{
			id: "insights4",
			title: "Outlooks | Aug 2019",
			text: "Transformational Markets: History Being Made",
			image: "assets/card/image-4.gif",
		},
		{
			id: "insights5",
			title: "E-Book | Aug 2018",
			text: "Financial Complexity & Nonlinear Dynamics",
			image: "assets/card/image-5.webp",
		},
		{
			id: "insights6",
			title: "Scenarios | Jan 2016",
			text: "The Market Economy In 2020. Emergence of a New Monetary Orthodoxy",
			image: "assets/card/image-6.webp",
		},
	],
	podcasts: [
		{
			id: "podcasts1",
			title: "Feb22. The Curious Learners",
			text: "Focus on investments in financial services across TradFi, DeFi and CeFi.",
			image: "assets/podcast/podcast-1.gif",
		},
		{
			id: "podcasts2",
			title: "Dec21. MacroVoices",
			text: "Plotting a Course for Digitization of Financial Markets.",
			image: "assets/podcast/podcast-2.gif",
		},
		{
			id: "podcasts3",
			title: "Nov21. The Curious Learners",
			text: "Podcast episode with Nikita Fadeev.",
			image: "assets/podcast/podcast-3.gif",
		},
		{
			id: "podcasts4",
			title: "Nov21. Resonance FM",
			text: "New Technologies Coming to the Rescue.",
			image: "assets/podcast/podcast-4.gif",
		},
		{
			id: "podcasts5",
			title: "Oct21. The Alternative Data Podcast",
			text: "Alternative data in Digital Lending.",
			image: "assets/podcast/podcast-5.gif",
		},
		{
			id: "podcasts6",
			title: "Jul21. N@ked Short Club",
			text: "Markets in 2025",
			image: "assets/podcast/podcast-6.gif",
		},
	],
	medias: [
		{
			id: "media1",
			title: "Sky News",
			date: "May 2022",
			text: "Sky News coverage of our Fasanara VC III launch.",
			logo: "assets/logo/skynews-logo.webp",
			media: "assets/media/skynews.webp",
			video: "assets/media/skynews-video.mp4",
		},
		{
			id: "media2",
			title: "Europe News",
			date: "Jan 2022",
			text: "A controversial EU plan to include nuclear and natural gas in its ranking of sustainable investments is confusing and could lead to further greenwashing, investors told CNBC. Fasanara Capital shared its opinion on this statement.",
			logo: "assets/logo/cnbc-logo.webp",
			media: "assets/media/cnbc.webp",
			video: "",
		},
		{
			id: "media3",
			title: "Industry Insights",
			date: "Dec 2021",
			text: "One of Fasanara’s goals for growing our fund was to tap into the massive benefits of DeFi without sacrificing our security protocols and policies. Fireblocks has enabled us to do so through their industry-leading security and expertise.",
			logo: "assets/logo/fireblock-logo.webp",
			media: "assets/media/fasanara.webp",
			video: "",
		},
	],
};

export default data;
